name: NuGet

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Tests"]
    types: [completed]

jobs:
  nuget:
    runs-on: windows-latest
    if: |
      github.event_name == 'workflow_dispatch' ||
      (github.event.workflow_run.conclusion == 'success' &&
       github.event.workflow_run.head_branch == 'main')
    steps:
    - uses: actions/checkout@v5
      with:
        ref: ${{ github.event.workflow_run.head_sha || github.sha }}
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 10.0.x
    - name: Install .NET MAUI
      shell: pwsh
      run: dotnet workload install maui --source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet10/nuget/v3/index.json --source https://api.nuget.org/v3/index.json
    - name: Workload update
      run: dotnet workload update
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c Release --no-restore
    - name: Test
      run: dotnet test -c Release --no-build --no-restore --verbosity normal
    - name: Build solution and generate NuGet package
      run: dotnet pack --no-build --no-restore -c Release -o out
    - name: Publish to NuGet
      run: dotnet nuget push **/*.nupkg --skip-duplicate --api-key ${{ secrets.NUGETTOKEN }} --source https://api.nuget.org/v3/index.json